# SPDX-License-Identifier: MIT
"""Reusable cocotb bus functional models for the SmartNIC verification tree."""

from .pcie_bfm import (
    PcieBar,
    PcieCompletion,
    PcieCompletionTimeout,
    PcieFunctionIdentity,
    PcieHostBfm,
    PcieMsixVector,
    PcieTlp,
)
from .roce_ethernet_bfm import (
    EthernetFrame,
    EthernetRoceBfm,
    Ipv4UdpPacket,
    ParsedRoceFrame,
    RoceBfmError,
    RoceOpcode,
    RocePacket,
)
from .host_memory_model import (
    DmaBuffer,
    DmaTransaction,
    HostMemoryError,
    HostMemoryModel,
    PatternKind,
)
from .rdma_scoreboard import (
    CompletionStatus,
    ExpectedWorkRequest,
    ObservedCqe,
    PacketObservation,
    QpType,
    RdmaScoreboard,
    ScoreboardError,
    SgeRef,
    WrOpcode,
)
from .rdma_coverage import (
    CongestionEvent,
    CoverageCategory,
    CoverageSummary,
    MessageSizeBin,
    MrPermission,
    QpState,
    RdmaCoverageCollector,
    SgeCountBin,
)

__all__ = [
    "CompletionStatus",
    "CongestionEvent",
    "CoverageCategory",
    "CoverageSummary",
    "DmaBuffer",
    "DmaTransaction",
    "EthernetFrame",
    "EthernetRoceBfm",
    "ExpectedWorkRequest",
    "HostMemoryError",
    "HostMemoryModel",
    "Ipv4UdpPacket",
    "MessageSizeBin",
    "MrPermission",
    "ObservedCqe",
    "PacketObservation",
    "PatternKind",
    "ParsedRoceFrame",
    "PcieBar",
    "PcieCompletion",
    "PcieCompletionTimeout",
    "PcieFunctionIdentity",
    "PcieHostBfm",
    "PcieMsixVector",
    "PcieTlp",
    "QpType",
    "QpState",
    "RdmaCoverageCollector",
    "RdmaScoreboard",
    "RoceBfmError",
    "RoceOpcode",
    "RocePacket",
    "ScoreboardError",
    "SgeRef",
    "SgeCountBin",
    "WrOpcode",
]
